# Generated by Django 5.2.13 on 2026-08-08 08:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('readers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Passage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(help_text='Stable id used by the app and by every exported data row.', max_length=64, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('category', models.CharField(default='Children Stories', max_length=80)),
                ('difficulty', models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], default='easy', max_length=10)),
                ('estimated_minutes', models.PositiveSmallIntegerField(default=3)),
                ('is_published', models.BooleanField(default=True, help_text="Unpublished passages stay hidden from the reader's Library.")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('title',),
            },
        ),
        migrations.CreateModel(
            name='Bookmark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_index', models.PositiveSmallIntegerField(default=0)),
                ('excerpt', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookmarks', to='readers.readerprofile')),
                ('passage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookmarks', to='passages.passage')),
            ],
            options={
                'ordering': ('-created_at',),
                'unique_together': {('reader', 'passage', 'page_index')},
            },
        ),
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile', models.CharField(blank=True, help_text='Reading condition to run this passage under, if fixed.', max_length=16)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('reader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='readers.readerprofile')),
                ('passage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='passages.passage')),
            ],
            options={
                'ordering': ('-assigned_at',),
                'unique_together': {('reader', 'passage')},
            },
        ),
        migrations.CreateModel(
            name='PassagePage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField(default=1)),
                ('body', models.TextField(help_text='Separate paragraphs with a blank line.')),
                ('passage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pages', to='passages.passage')),
            ],
            options={
                'ordering': ('order',),
                'unique_together': {('passage', 'order')},
            },
        ),
    ]
