# Generated by Django 5.2.13 on 2026-08-08 09:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuizQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField(default=1)),
                ('kind', models.CharField(choices=[('multiple_choice', 'Multiple choice'), ('true_false', 'True / False')], default='multiple_choice', max_length=20)),
                ('prompt', models.TextField()),
                ('options', models.JSONField(default=list, help_text='Answer options, e.g. ["একটা ভেজা পাখি", "একটা রঙিন ছাতা"].')),
                ('correct_index', models.PositiveSmallIntegerField(default=0)),
                ('passage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='passages.passage')),
            ],
            options={
                'ordering': ('order',),
                'unique_together': {('passage', 'order')},
            },
        ),
    ]
