# Generated by Django 5.2.13 on 2026-08-08 08:45

import django.db.models.deletion
import readers.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReaderProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('participant_id', models.CharField(default=readers.models.generate_participant_id, help_text='Matches the participant_id on every synced session row.', max_length=32, unique=True)),
                ('display_name', models.CharField(max_length=120)),
                ('age', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('class_grade', models.CharField(blank=True, max_length=40)),
                ('school', models.CharField(blank=True, max_length=160)),
                ('starting_profile', models.CharField(default='recommended', help_text='Reading condition this reader starts a session in.', max_length=16)),
                ('claimed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('therapist', models.ForeignKey(blank=True, limit_choices_to={'role': 'therapist'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='readers', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reader_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('display_name',),
            },
        ),
        migrations.CreateModel(
            name='ReaderNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('reader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='readers.readerprofile')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('therapist_added', 'Therapist added you'), ('passage_assigned', 'Passage assigned'), ('general', 'General')], default='general', max_length=32)),
                ('title', models.CharField(max_length=160)),
                ('body', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['recipient', 'read_at'], name='readers_not_recipie_7644b0_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='readerprofile',
            index=models.Index(fields=['therapist'], name='readers_rea_therapi_e35afb_idx'),
        ),
    ]
