# Generated by Django 5.2.13 on 2026-08-08 09:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('readers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReaderSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('values', models.JSONField(default=dict, help_text='The ReadingSettings.toMap() payload from the app.')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reader', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to='readers.readerprofile')),
            ],
            options={
                'verbose_name_plural': 'reader settings',
            },
        ),
    ]
