# Generated by Django 5.2.3 on 2026-08-10 02:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('readers', '0002_readersettings'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='kind',
            field=models.CharField(choices=[('therapist_added', 'Therapist added you'), ('passage_assigned', 'Passage assigned'), ('supervision_requested', 'Therapist asked to add you'), ('supervision_accepted', 'Reader accepted'), ('supervision_declined', 'Reader declined'), ('general', 'General')], default='general', max_length=32),
        ),
        migrations.CreateModel(
            name='SupervisionRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Waiting for the reader'), ('accepted', 'Accepted'), ('declined', 'Declined'), ('superseded', 'Reader accepted someone else')], default='pending', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('reader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supervision_requests', to='readers.readerprofile')),
                ('therapist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supervision_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.AddField(
            model_name='notification',
            name='supervision_request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='readers.supervisionrequest'),
        ),
        migrations.AddIndex(
            model_name='supervisionrequest',
            index=models.Index(fields=['reader', 'status'], name='readers_sup_reader__5c792b_idx'),
        ),
        migrations.AddConstraint(
            model_name='supervisionrequest',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'pending')), fields=('reader', 'therapist'), name='one_pending_supervision_request_per_pair'),
        ),
    ]
