# Generated by Django 5.2.13 on 2026-08-08 08:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('readers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudySession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(db_index=True, max_length=64, unique=True)),
                ('participant_id', models.CharField(db_index=True, max_length=32)),
                ('passage_id', models.CharField(db_index=True, max_length=64)),
                ('started_at', models.DateTimeField()),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('profile', models.CharField(blank=True, max_length=16)),
                ('total_reading_seconds', models.FloatField(blank=True, null=True)),
                ('words_read', models.PositiveIntegerField(blank=True, null=True)),
                ('read_aloud_on', models.BooleanField(default=False)),
                ('audio_duration_seconds', models.FloatField(blank=True, null=True)),
                ('quiz_score', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('quiz_total', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('ease_stars', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('audio_help_stars', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('helpful_settings', models.TextField(blank=True)),
                ('suggestion', models.TextField(blank=True)),
                ('sus_score', models.FloatField(blank=True, null=True)),
                ('synced_at', models.DateTimeField(auto_now=True)),
                ('reader', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='readers.readerprofile')),
            ],
            options={
                'ordering': ('-started_at',),
            },
        ),
        migrations.CreateModel(
            name='SettingsChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('at', models.DateTimeField()),
                ('key', models.CharField(max_length=64)),
                ('old_value', models.CharField(blank=True, max_length=120)),
                ('new_value', models.CharField(blank=True, max_length=120)),
                ('profile', models.CharField(max_length=16)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='settings_changes', to='sync.studysession')),
            ],
            options={
                'ordering': ('at',),
            },
        ),
        migrations.CreateModel(
            name='QuizAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_index', models.PositiveSmallIntegerField()),
                ('selected_index', models.SmallIntegerField()),
                ('correct', models.BooleanField()),
                ('time_seconds', models.FloatField()),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_answers', to='sync.studysession')),
            ],
            options={
                'ordering': ('question_index',),
            },
        ),
        migrations.CreateModel(
            name='PageTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_index', models.PositiveSmallIntegerField()),
                ('seconds', models.FloatField()),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='page_times', to='sync.studysession')),
            ],
            options={
                'ordering': ('page_index',),
            },
        ),
        migrations.CreateModel(
            name='SusResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_index', models.PositiveSmallIntegerField()),
                ('response', models.PositiveSmallIntegerField()),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sus_responses', to='sync.studysession')),
            ],
            options={
                'ordering': ('item_index',),
            },
        ),
        migrations.CreateModel(
            name='TlxResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subscale', models.CharField(max_length=32)),
                ('value', models.PositiveSmallIntegerField()),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tlx_responses', to='sync.studysession')),
            ],
            options={
                'ordering': ('subscale',),
            },
        ),
        migrations.AddIndex(
            model_name='studysession',
            index=models.Index(fields=['participant_id', '-started_at'], name='sync_studys_partici_b151c3_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='quizanswer',
            unique_together={('session', 'question_index')},
        ),
        migrations.AlterUniqueTogether(
            name='pagetime',
            unique_together={('session', 'page_index')},
        ),
        migrations.AlterUniqueTogether(
            name='susresponse',
            unique_together={('session', 'item_index')},
        ),
        migrations.AlterUniqueTogether(
            name='tlxresponse',
            unique_together={('session', 'subscale')},
        ),
    ]
